CREATE DATABASE Minions

USE [Minions]

CREATE TABLE [Minions](
    Id      INT,
    [Name]  VARCHAR(100),
    Age     INT
)

CREATE TABLE [Towns]( 
    Id INT PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(100)
)

ALTER TABLE Minions
ALTER COLUMN Id INT NOT NULL;


ALTER TABLE Minions
ADD CONSTRAINT PK_Id  PRIMARY KEY (Id);
